### ISSUE TITLE
The left and right margin widths are swapped

### ISSUE THREAD

**Issue by rowlesmr** [HappyCerberus/book-cpp-algorithms#10]
The title page (page 3 in the PDF) is normally on the right side of book when printed/open, meaning that the wide margin should be on the left to allow for binding. Currently, the wide margin is on the right, meaning that the title page would be on the left when printed. This may be intentional, but doesn't line up with being the third page; cover (right), inside cover (left), title page (right).

**Comment by HappyCerberus** [comment]
They shouldn't be swapped (the margin notes go on the outer margin), but you are correct that the "title" page shouldn't follow the margin configuration.

I will need to figure out how to fix this (I didn't fiddle with this yet).

**Comment by HappyCerberus** [comment]
Ok, this turns out to be a much bigger hassle than I imagined 😅

I will leave it as is for now.

**Comment by rowlesmr** [comment]
I've had those ones before! No worries  :)
