### ISSUE TITLE
Missing close paren for `lower_bound`

### ISSUE THREAD

**Issue by StephanTLavavej** [HappyCerberus/book-cpp-algorithms#9]
There's a missing close paren at the end of this sentence:

https://github.com/HappyCerberus/book-cpp-algorithms/blob/f27fd58c89ee1ca52d70089d1629239a0c85adff/chapters/03_algorithms_05_divide.tex#L13

**Comment by HappyCerberus** [comment]
Thanks for the spot. 👍 Fixed in code.
I will do a proper PDF update release later.
